AWSTemplateFormatVersion: 2010-09-09
# Este stack genera una VPC y sus componentes de redes
Resources:
  # Creacion de la VPC:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC2" ]]
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Propierties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
    
        
  

